<?php
/**
 * @var $this Bubble_Queryfier_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('http://i.imgur.com/NtYmWIh.png') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="https://github.com/jreinke/magento-suffix-static-files" target="_blank" style="float:right;">
            <img src="http://i.imgur.com/QVKwCFx.png" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('bubble_queryfier')->__('Bubble Queryfier helps you adding a query parameter to static files (.css, .js), this will force cache refresh on client-side.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('bubble_queryfier')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('bubble_queryfier')->__('http://bubbleco.de/en/2012/08/28/magento-a-module-to-force-static-files-reloading/')); ?>" target="_blank"><?php echo $this->helper('bubble_queryfier')->__('here'); ?></a>.</p>
    </div>
</div>